baseurl = "https://wolf-family-cookbook.gitlab.io"
contentdir    = "content"
layoutdir     = "layouts"
publishdir    = "public"
title = "Wolf Family Cookbook"
canonifyurls  = true

DefaultContentLanguage = "en"
theme = "docdock"
paginate = 20
pygmentsstyle = "monokai"
pygmentscodefences = true
pygmentscodefencesguesssyntax = true
pygmentsOptions = "linenos=table"

[permalinks]
posts = "/posts/:year/:month/:title"

[params]
themeStyle = "original"
author = "Alex Wolf"
description = "Recipies for the Wolf family"
keywords = "recipes"
favicon_32 = "/images/favicon-32x32.png"
favicon_16 = "/images/favicon-16x16.png"
hidecredits = false
hidecopyright = false
showNavTitle = false
custom_css = [
  "style.css"
]

# [menu]
#   [[menu.main]]
#   name = "Home"
#   weight = 1.0
#   url = "/"
#   [[menu.main]]
#   name = "Breakfast"
#   weight = 2.0
#   url = "/breakfast/"
#   [[menu.main]]
#   name = "Lunch & Dinner"
#   weight = 3.0
#   url = "/lunch-dinner/"
#   [[menu.main]]
#   name = "Sides"
#   weight = 4.0
#   url = "/sides/"
#   [[menu.main]]
#   name = "Dips & Sauses"
#   weight = 5.0
#   url = "/dips-sauces/"
#   [[menu.main]]
#   name = "Desserts"
#   weight = 6.0
#   url = "/dessert/"
# [taxonomies]
# category = "category"
# cusine = "cuisine"
# tag = "tags"